In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')

In [70]:
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')
submission = pd.read_csv('data/sample_submission.csv')

train.head(3)
train.tail(3)

,id,X00,X01,X02,X03,X04,X05,X06,X07,X08,...,Y09,Y10,Y11,Y12,Y13,Y14,Y15,Y16,Y17,Y18
4749,4749,19.7,987.7,0.9,0.6,0.0,1006.9,987.6,21.4,1007.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.5
4750,4750,19.4,987.7,0.9,0.8,0.0,1006.9,987.8,21.3,1007.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.5
4751,4751,19.1,987.6,1.0,0.3,0.0,1006.8,987.8,21.2,1007.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0

In [106]:
train['date'] = pd.PeriodIndex(start='2020-01-01', end=None, periods=len(train), freq='10Min')
test['date'] = pd.PeriodIndex(start='2020-02-03', end=None, periods=len(test), freq='10Min')
train.tail()

,id,X00,X01,X02,X03,X04,X05,X06,X07,X08,...,Y10,Y11,Y12,Y13,Y14,Y15,Y16,Y17,Y18,date
date,,,,,,,,,,,,,,,,,,,,,
2020-02-02 23:10,4747,19.9,987.6,0.9,0.8,0.0,1006.9,987.7,21.7,1007.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.5,2020-02-02 23:10
2020-02-02 23:20,4748,19.9,987.6,0.5,0.7,0.0,1006.8,987.7,21.6,1007.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.5,2020-02-02 23:20
2020-02-02 23:30,4749,19.7,987.7,0.9,0.6,0.0,1006.9,987.6,21.4,1007.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.5,2020-02-02 23:30
2020-02-02 23:40,4750,19.4,987.7,0.9,0.8,0.0,1006.9,987.8,21.3,1007.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.5,2020-02-02 23:40
2020-02-02 23:50,4751,19.1,987.6,1.0,0.3,0.0,1006.8,987.8,21.2,1007.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,2020-02-02 23:50

In [107]:
train.set_index('date', drop=True, inplace=True)
train.tail()

,id,X00,X01,X02,X03,X04,X05,X06,X07,X08,...,Y09,Y10,Y11,Y12,Y13,Y14,Y15,Y16,Y17,Y18
date,,,,,,,,,,,,,,,,,,,,,
2020-02-02 23:10,4747,19.9,987.6,0.9,0.8,0.0,1006.9,987.7,21.7,1007.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.5
2020-02-02 23:20,4748,19.9,987.6,0.5,0.7,0.0,1006.8,987.7,21.6,1007.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.5
2020-02-02 23:30,4749,19.7,987.7,0.9,0.6,0.0,1006.9,987.6,21.4,1007.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.5
2020-02-02 23:40,4750,19.4,987.7,0.9,0.8,0.0,1006.9,987.8,21.3,1007.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.5
2020-02-02 23:50,4751,19.1,987.6,1.0,0.3,0.0,1006.8,987.8,21.2,1007.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0

In [108]:
test.set_index('date', drop=True, inplace=True)
test.tail()

,id,X00,X01,X02,X03,X04,X05,X06,X07,X08,...,X30,X31,X32,X33,X34,X35,X36,X37,X38,X39
date,,,,,,,,,,,,,,,,,,,,,
2020-04-22 23:10,16267,25.7,993.2,3.9,3.8,0.0,1011.7,993.8,26.3,1013.3,...,76.6,23.6,24.4,1013.0,19.56,169.6,0.0,79.7,67.5,0.5
2020-04-22 23:20,16268,25.6,993.2,3.0,3.0,0.0,1011.7,993.8,26.3,1013.3,...,76.7,25.3,24.4,1012.9,19.56,175.9,0.0,79.6,67.9,0.5
2020-04-22 23:30,16269,25.6,993.2,3.8,2.5,0.0,1011.9,993.7,26.2,1013.2,...,77.1,24.9,24.3,1012.9,19.56,204.7,0.0,79.2,68.3,0.5
2020-04-22 23:40,16270,25.5,993.2,2.4,2.8,0.0,1011.8,993.7,26.1,1013.2,...,77.3,25.3,24.2,1012.9,19.56,174.2,0.0,80.1,68.8,0.5
2020-04-22 23:50,16271,25.4,993.2,3.0,3.5,0.0,1011.9,993.6,26.0,1013.1,...,76.6,25.4,24.3,1012.9,19.56,200.7,0.0,80.2,68.9,0.5

In [109]:
# 지역으로 'id',
train_A = train[['X01','X02','X04','X05','X11','X12','X13','X00']]
train_B = train[['X06','X03','X10','X08','X14','X20','X15','X07']]
train_C = train[['X22','X18','X21','X09','X16','X30','X17','X28']]
train_D = train[['X27','X24','X36','X23','X19','X37','X25','X31']]
train_E = train[['X29','X26','X39','X33','X34','X38','X35','X32']]

train_A.head()

                    X01  X02  X04     X05  X11   X12    X13  X00
date
2020-01-01 00:00  988.8  1.2  0.0  1009.3  0.0  82.4   71.3  9.7
2020-01-01 00:10  988.9  1.7  0.0  1009.3  0.0  81.2  121.8  9.3
2020-01-01 00:20  989.0  1.1  0.0  1009.2  0.0  86.1  232.0  9.4
2020-01-01 00:30  988.9  1.5  0.0  1009.2  0.0  87.7    0.0  9.4
2020-01-01 00:40  988.9  0.8  0.0  1009.2  0.0  88.9    0.0  9.2

In [110]:
test_A = test[['X01','X02','X04','X05','X11','X12','X13','X00']]
test_B = test[['X06','X03','X10','X08','X14','X20','X15','X07']]
test_C = test[['X22','X18','X21','X09','X16','X30','X17','X28']]
test_D = test[['X27','X24','X36','X23','X19','X37','X25','X31']]
test_E = test[['X29','X26','X39','X33','X34','X38','X35','X32']]

In [111]:
train_A = train_A.rename(columns={
    'X01':'AirPressure'
    ,'X02':'WindSpeed'
    ,'X04':'Precipitation'
    ,'X05':'SeaPressure'
    ,'X11':'Insolation'
    ,'X12':'Humidity'
    ,'X13':'WindDirection'
    ,'X00':'target'})

train_B = train_A.rename(columns={
    'X06':'AirPressure'
    ,'X03':'WindSpeed'
    ,'X10':'Precipitation'
    ,'X08':'SeaPressure'
    ,'X14':'Insolation'
    ,'X20':'Humidity'
    ,'X15':'WindDirection'
    ,'X07':'target'})

train_C = train_A.rename(columns={
    'X22':'AirPressure'
    ,'X18':'WindSpeed'
    ,'X21':'Precipitation'
    ,'X09':'SeaPressure'
    ,'X16':'Insolation'
    ,'X30':'Humidity'
    ,'X17':'WindDirection'
    ,'X28':'target'})

train_D = train_A.rename(columns={
    'X27':'AirPressure'
    ,'X24':'WindSpeed'
    ,'X36':'Precipitation'
    ,'X23':'SeaPressure'
    ,'X19':'Insolation'
    ,'X37':'Humidity'
    ,'X25':'WindDirection'
    ,'X31':'target'})

train_E = train_A.rename(columns={
    'X29':'AirPressure'
    ,'X26':'WindSpeed'
    ,'X39':'Precipitation'
    ,'X33':'SeaPressure'
    ,'X34':'Insolation'
    ,'X38':'Humidity'
    ,'X35':'WindDirection'
    ,'X32':'target'})

train_A

,AirPressure,WindSpeed,Precipitation,SeaPressure,Insolation,Humidity,WindDirection,target
date,,,,,,,,
2020-01-01 00:00,988.8,1.2,0.0,1009.3,0.00,82.4,71.3,9.7
2020-01-01 00:10,988.9,1.7,0.0,1009.3,0.00,81.2,121.8,9.3
2020-01-01 00:20,989.0,1.1,0.0,1009.2,0.00,86.1,232.0,9.4
2020-01-01 00:30,988.9,1.5,0.0,1009.2,0.00,87.7,0.0,9.4
2020-01-01 00:40,988.9,0.8,0.0,1009.2,0.00,88.9,0.0,9.2
2020-01-01 00:50,988.9,1.3,0.0,1009.1,0.00,90.7,222.0,9.1
2020-01-01 01:00,988.8,2.4,0.0,1009.1,0.00,90.2,257.8,9.1
2020-01-01 01:10,988.9,1.0,0.0,1009.2,0.00,91.9,226.4,8.9
2020-01-01 01:20,988.9,1.5,0.0,1009.2,0.00,92.2,215.0,9.0
2020-01-01 01:30,988.9,1.4,0.0,1009.4,0.00,92.7,214.4,8.8
2020-01-01 01:40,989.0,1.9,0.0,1009.2,0.00,92.5,197.9,8.7
2020-01-01 01:50,988.9,1.6,0.0,1009.0,0.00,93.0,262.1,8.8
2020-01-01 02:00,988.8,1.9,0.0,1008.9,0.00,92.7,250.0,8.7
2020-01-01 02:10,988.8,1.5,0.0,1008.8,0.00,93.1,193.2,8.6
2020-01-01 02:20,988.7,1.6,0.0,1008.7,0.00,93.2,231.8,9.2
2020-01-01 02:30,988.6,1.9,0.0,1008.7,0.00,94.0,227.9,9.1
2020-01-01 02:40,988.6,2.5,0.0,1008.8,0.00,93.5,156.5,9.3
2020-01-01 02:50,988.5,1.3,0.0,1008.8,0.00,93.8,207.3,9.0
2020-01-01 03:00,988.5,1.7,0.0,1008.7,0.00,94.3,0.0,9.0
2020-01-01 03:10,988.4,2.6,0.0,1008.7,0.00,94.6,199.5,8.7
2020-01-01 03:20,988.3,3.0,0.0,1008.6,0.00,94.8,163.1,8.8
2020-01-01 03:30,988.3,2.3,0.0,1008.4,0.00,94.8,205.6,8.6
2020-01-01 03:40,988.3,3.0,0.0,1008.5,0.00,95.0,0.0,8.4
2020-01-01 03:50,988.3,1.6,0.0,1008.6,0.00,95.3,18.1,8.4
2020-01-01 04:00,988.2,3.0,0.0,1008.6,0.00,95.6,0.0,8.6
2020-01-01 04:10,988.3,3.1,0.0,1008.6,0.00,96.0,319.0,8.5
2020-01-01 04:20,988.4,2.4,0.0,1008.7,0.00,95.8,307.4,8.5
2020-01-01 04:30,988.4,2.3,0.0,1008.6,0.00,96.0,281.4,8.6
2020-01-01 04:40,988.3,2.8,0.0,1008.6,0.00,96.0,279.8,8.9
2020-01-01 04:50,988.3,2.2,0.0,1008.6,0.00,96.2,214.5,8.8
...,...,...,...,...,...,...,...,...
2020-02-02 19:00,985.3,0.3,0.0,1004.4,23.70,84.6,21.5,25.7
2020-02-02 19:10,985.4,2.2,0.0,1004.4,23.77,86.8,2.7,25.4
2020-02-02 19:20,985.5,0.7,0.0,1004.4,23.79,85.8,317.9,25.2
2020-02-02 19:30,985.7,1.7,0.0,1004.6,23.82,84.1,37.2,25.2
2020-02-02 19:40,985.6,1.5,0.0,1004.6,23.84,86.5,7.1,25.0
2020-02-02 19:50,985.8,1.6,0.0,1004.8,23.86,87.5,253.1,24.9
2020-02-02 20:00,985.9,2.2,0.0,1004.9,23.86,87.2,360.0,24.7
2020-02-02 20:10,986.0,2.2,0.0,1005.0,23.87,86.7,32.1,24.5
2020-02-02 20:20,986.1,1.4,0.0,1005.1,23.87,86.2,341.3,24.2
2020-02-02 20:30,986.1,1.0,0.0,1005.3,23.87,82.1,218.7,24.0
2020-02-02 20:40,986.5,1.2,0.0,1005.4,23.87,82.9,232.5,24.1
2020-02-02 20:50,986.9,1.5,0.0,1005.6,23.87,85.4,321.6,23.4
2020-02-02 21:00,987.0,0.8,0.0,1005.7,23.88,84.7,289.3,23.2
2020-02-02 21:10,987.2,1.3,0.0,1005.8,23.88,91.4,66.4,22.0
2020-02-02 21:20,987.3,2.5,0.0,1006.0,23.88,92.6,350.3,21.7
2020-02-02 21:30,987.5,1.8,0.0,1006.1,23.88,93.2,61.2,21.6
2020-02-02 21:40,987.7,2.0,0.0,1006.3,23.88,93.9,333.2,21.5
2020-02-02 21:50,987.7,2.6,0.0,1006.4,23.88,93.6,340.2,21.3
2020-02-02 22:00,987.7,1.4,0.0,1006.6,23.88,93.4,359.6,21.1
2020-02-02 22:10,987.7,1.6,0.0,1006.6,23.88,93.6,347.1,21.0
2020-02-02 22:20,987.7,0.2,0.0,1006.6,23.88,93.6,29.2,20.9
2020-02-02 22:30,987.6,2.6,0.0,1006.8,23.88,94.0,14.8,20.8
2020-02-02 22:40,987.7,1.1,0.0,1006.8,23.88,94.5,304.7,20.5
2020-02-02 22:50,987.8,1.1,0.0,1006.9,23.88,94.7,222.9,20.2
2020-02-02 23:00,987.9,0.3,0.0,1006.9,23.88,95.2,298.4,20.1
2020-02-02 23:10,987.6,0.9,0.0,1006.9,23.88,95.3,333.1,19.9
2020-02-02 23:20,987.6,0.5,0.0,1006.8,23.88,95.6,216.4,19.9
2020-02-02 23:30,987.7,0.9,0.0,1006.9,23.88,95.9,127.8,19.7
2020-02-02 23:40,987.7,0.9,0.0,1006.9,23.88,95.9,323.8,19.4
2020-02-02 23:50,987.6,1.0,0.0,1006.8,23.88,96.2,0.0,19.1

In [112]:
test_A = test_A.rename(columns={
    'X01':'AirPressure'
    ,'X02':'WindSpeed'
    ,'X04':'Precipitation'
    ,'X05':'SeaPressure'
    ,'X11':'Insolation'
    ,'X12':'Humidity'
    ,'X13':'WindDirection'
    ,'X00':'target'})

test_B = test_A.rename(columns={
    'X06':'AirPressure'
    ,'X03':'WindSpeed'
    ,'X10':'Precipitation'
    ,'X08':'SeaPressure'
    ,'X14':'Insolation'
    ,'X20':'Humidity'
    ,'X15':'WindDirection'
    ,'X07':'target'})

test_C = test_A.rename(columns={
    'X22':'AirPressure'
    ,'X18':'WindSpeed'
    ,'X21':'Precipitation'
    ,'X09':'SeaPressure'
    ,'X16':'Insolation'
    ,'X30':'Humidity'
    ,'X17':'WindDirection'
    ,'X28':'target'})

test_D = test_A.rename(columns={
    'X27':'AirPressure'
    ,'X24':'WindSpeed'
    ,'X36':'Precipitation'
    ,'X23':'SeaPressure'
    ,'X19':'Insolation'
    ,'X37':'Humidity'
    ,'X25':'WindDirection'
    ,'X31':'target'})

test_E = test_A.rename(columns={
    'X29':'AirPressure'
    ,'X26':'WindSpeed'
    ,'X39':'Precipitation'
    ,'X33':'SeaPressure'
    ,'X34':'Insolation'
    ,'X38':'Humidity'
    ,'X35':'WindDirection'
    ,'X32':'target'})

test_A

,AirPressure,WindSpeed,Precipitation,SeaPressure,Insolation,Humidity,WindDirection,target
date,,,,,,,,
2020-02-03 00:00,987.4,1.5,0.0,1006.8,0.00,96.1,333.6,18.7
2020-02-03 00:10,987.4,1.1,0.0,1006.7,0.00,96.2,335.5,18.8
2020-02-03 00:20,987.4,1.3,0.0,1006.6,0.00,96.4,0.0,19.0
2020-02-03 00:30,987.4,2.3,0.0,1006.6,0.00,96.5,252.9,18.7
2020-02-03 00:40,987.4,1.1,0.0,1006.7,0.00,96.6,238.2,18.4
2020-02-03 00:50,987.4,1.3,0.0,1006.8,0.00,96.6,0.0,18.6
2020-02-03 01:00,987.3,1.0,0.0,1006.7,0.00,96.9,230.9,18.6
2020-02-03 01:10,987.5,1.5,0.0,1006.7,0.00,96.8,200.6,18.7
2020-02-03 01:20,987.5,1.2,0.0,1006.8,0.00,96.8,241.8,18.5
2020-02-03 01:30,987.5,1.5,0.0,1006.8,0.00,96.9,206.2,18.5
2020-02-03 01:40,987.5,0.9,0.0,1007.0,0.00,97.0,257.3,18.7
2020-02-03 01:50,987.4,1.1,0.0,1006.9,0.00,97.0,199.9,18.9
2020-02-03 02:00,987.4,0.3,0.0,1006.9,0.00,97.1,215.5,19.2
2020-02-03 02:10,987.4,0.1,0.0,1006.9,0.00,97.1,208.5,19.4
2020-02-03 02:20,987.3,0.3,0.0,1006.9,0.00,97.1,220.5,19.5
2020-02-03 02:30,987.4,0.0,0.0,1006.9,0.00,97.2,178.4,19.5
2020-02-03 02:40,987.4,0.0,0.0,1006.9,0.00,97.1,325.9,19.4
2020-02-03 02:50,987.4,1.0,0.0,1006.8,0.00,97.2,317.7,19.4
2020-02-03 03:00,987.4,1.0,0.0,1006.9,0.00,97.1,299.5,19.4
2020-02-03 03:10,987.4,0.8,0.0,1007.0,0.00,97.2,297.7,19.5
2020-02-03 03:20,987.4,0.8,0.0,1007.0,0.00,97.2,284.1,19.4
2020-02-03 03:30,987.5,0.7,0.0,1007.1,0.00,97.3,216.5,19.5
2020-02-03 03:40,987.7,0.6,0.0,1007.3,0.00,97.3,245.3,19.5
2020-02-03 03:50,987.8,1.7,0.0,1007.4,0.00,97.3,0.0,19.5
2020-02-03 04:00,987.9,0.9,0.0,1007.5,0.00,97.2,0.0,19.5
2020-02-03 04:10,988.0,1.0,0.0,1007.5,0.00,97.4,182.4,19.5
2020-02-03 04:20,988.0,0.6,0.0,1007.6,0.00,97.3,0.0,19.5
2020-02-03 04:30,988.1,0.6,0.0,1007.7,0.00,97.4,221.3,19.5
2020-02-03 04:40,988.2,0.8,0.0,1007.8,0.00,97.6,336.3,19.5
2020-02-03 04:50,988.3,0.7,0.0,1007.9,0.00,97.6,0.0,19.6
...,...,...,...,...,...,...,...,...
2020-04-22 19:00,992.0,0.4,0.0,1010.9,17.02,80.8,31.9,27.4
2020-04-22 19:10,992.1,2.0,0.0,1011.0,17.03,81.4,25.1,27.4
2020-04-22 19:20,992.2,0.7,0.0,1011.0,17.04,84.1,18.4,27.0
2020-04-22 19:30,992.4,1.3,0.0,1011.2,17.04,86.7,15.2,27.0
2020-04-22 19:40,992.5,0.7,0.0,1011.4,17.04,85.6,18.1,27.2
2020-04-22 19:50,992.6,0.4,0.0,1011.4,17.05,86.3,317.6,27.1
2020-04-22 20:00,992.6,0.1,0.0,1011.4,17.05,84.0,66.9,27.0
2020-04-22 20:10,992.7,1.4,0.0,1011.5,17.06,88.2,9.1,27.0
2020-04-22 20:20,992.8,1.4,0.0,1011.6,17.06,87.1,217.6,26.8
2020-04-22 20:30,992.9,0.0,0.0,1011.6,17.07,89.9,0.0,26.7
2020-04-22 20:40,992.8,0.0,0.0,1011.7,17.09,90.2,35.0,26.7
2020-04-22 20:50,992.9,0.0,0.0,1011.7,17.09,91.0,93.3,26.4
2020-04-22 21:00,992.9,0.0,0.0,1011.8,17.10,91.1,24.5,26.4
2020-04-22 21:10,993.0,0.0,0.0,1011.8,17.10,91.2,49.9,26.4
2020-04-22 21:20,993.0,0.9,0.0,1011.8,17.10,91.4,48.5,26.5
2020-04-22 21:30,993.1,1.3,0.0,1011.8,17.10,92.6,0.0,26.5
2020-04-22 21:40,993.1,1.8,0.0,1011.8,17.10,92.9,316.1,26.5
2020-04-22 21:50,993.2,0.6,0.0,1011.9,17.10,93.7,0.0,26.3
2020-04-22 22:00,993.3,2.3,0.0,1011.8,17.10,93.2,56.9,26.2
2020-04-22 22:10,993.3,3.4,0.0,1011.9,17.10,94.0,45.1,26.2
2020-04-22 22:20,993.3,3.4,0.0,1011.9,17.10,93.0,48.7,26.0
2020-04-22 22:30,993.3,4.2,0.0,1011.9,17.10,93.0,64.3,25.7
2020-04-22 22:40,993.3,4.2,0.0,1011.9,17.10,93.6,66.5,25.9
2020-04-22 22:50,993.3,3.7,0.0,1011.8,17.10,93.3,71.8,25.8
2020-04-22 23:00,993.2,3.9,0.0,1011.7,17.10,90.2,61.7,25.7
2020-04-22 23:10,993.2,3.9,0.0,1011.7,17.10,88.1,65.6,25.7
2020-04-22 23:20,993.2,3.0,0.0,1011.7,17.10,75.5,51.9,25.6
2020-04-22 23:30,993.2,3.8,0.0,1011.9,17.10,77.5,29.0,25.6
2020-04-22 23:40,993.2,2.4,0.0,1011.8,17.10,74.1,30.0,25.5
2020-04-22 23:50,993.2,3.0,0.0,1011.9,17.10,73.3,27.6,25.4

In [113]:
import statsmodels.api as sm

In [118]:
arima_A = sm.tsa.statespace.SARIMAX(train_A['Insolation'],
                                  order=(2,1,1),
                                  seasonal_order=(0,1,0,12),
                                  enforce_stationarity=False,
                                  enforce_invertibility=False)

ValueError: Invalid value for design matrix. Requires a 2- or 3-dimensional array, got 1 dimensions

In [119]:
arima_B = sm.tsa.statespace.SARIMAX(train_B['Insolation'],
                                  order=(2,1,1),
                                  seasonal_order=(0,1,0,12),
                                  enforce_stationarity=False,
                                  enforce_invertibility=False)
arima_C = sm.tsa.statespace.SARIMAX(train_C['Insolation'],
                                  order=(2,1,1),
                                  seasonal_order=(0,1,0,12),
                                  enforce_stationarity=False,
                                  enforce_invertibility=False)
arima_D = sm.tsa.statespace.SARIMAX(train_D['Insolation'],
                                  order=(2,1,1),
                                  seasonal_order=(0,1,0,12),
                                  enforce_stationarity=False,
                                  enforce_invertibility=False)
arima_E = sm.tsa.statespace.SARIMAX(train_E['Insolation'],
                                  order=(2,1,1),
                                  seasonal_order=(0,1,0,12),
                                  enforce_stationarity=False,
                                  enforce_invertibility=False)

In [120]:
arima_result_A = arima_A.fit()
arima_result_B = arima_B.fit()
arima_result_C = arima_B.fit()
arima_result_D = arima_D.fit()
arima_result_E = arima_E.fit()

In [121]:
test['A'] = arima_result_A.predict(start='2020-02-03', end='2020-04-22', freq='10Min', dynamic=True)
test['B'] = arima_result_B.predict(start='2020-02-03', end='2020-04-22', freq='10Min', dynamic=True)
test['C'] = arima_result_C.predict(start='2020-02-03', end='2020-04-22', freq='10Min', dynamic=True)
test['D'] = arima_result_D.predict(start='2020-02-03', end='2020-04-22', freq='10Min', dynamic=True)
test['E'] = arima_result_E.predict(start='2020-02-03', end='2020-04-22', freq='10Min', dynamic=True)

In [122]:
test.head()

,id,X00,X01,X02,X03,X04,X05,X06,X07,X08,...,X35,X36,X37,X38,X39,A,B,C,D,E
date,,,,,,,,,,,,,,,,,,,,,
2020-02-03 00:00,4752,18.7,987.4,1.5,1.3,0.0,1006.8,987.7,21.1,1007.5,...,194.7,0.0,84.0,59.9,0.0,23.884396,23.884396,23.884396,23.884396,23.884396
2020-02-03 00:10,4753,18.8,987.4,1.1,1.2,0.0,1006.7,987.7,21.2,1007.5,...,173.1,0.0,84.0,60.5,0.0,23.888641,23.888641,23.888641,23.888641,23.888641
2020-02-03 00:20,4754,19.0,987.4,1.3,1.2,0.0,1006.6,987.6,21.2,1007.4,...,208.6,0.0,85.0,60.8,0.0,23.892571,23.892571,23.892571,23.892571,23.892571
2020-02-03 00:30,4755,18.7,987.4,2.3,0.8,0.0,1006.6,987.6,21.1,1007.4,...,185.0,0.0,85.8,61.2,0.0,23.896204,23.896204,23.896204,23.896204,23.896204
2020-02-03 00:40,4756,18.4,987.4,1.1,0.7,0.0,1006.7,987.7,20.9,1007.5,...,162.8,0.0,87.3,61.7,0.0,23.899561,23.899561,23.899561,23.899561,23.899561

In [ ]:
from sklearn.model_selection import train_test_split, KFold, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(train , target ,test_size=0.3, shuffle=True, random_state=156)

In [ ]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

In [ ]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

In [ ]:
li_reg = LinearRegression(
    fit_intercept=True, # 절편값 계산, False: 절편 사용되지 않고 0 
    normalize=False, # fit_intercept=True 일때만 사용, 회귀 수행 전 정규화 수행
    copy_X=True,
    n_jobs=None,
)

lo_reg = LogisticRegression()

rf_reg = RandomForestRegressor(random_state=0, n_estimators=1000)

gb_reg = GradientBoostingRegressor(random_state=0, n_estimators=1000)

dt_reg = DecisionTreeRegressor(random_state=0, max_depth=4)
rf_reg = RandomForestRegressor(random_state=0, n_estimators=1000)
xgb_reg = XGBRegressor(n_estimators=1000)
lgb_reg = LGBMRegressor(n_estimators=1000)

In [ ]:
li_reg.fit(X_train ,y_train)
lo_reg.fit(X_train ,y_train.astype('int'))
rf_reg.fit(X_train ,y_train)
gb_reg.fit(X_train ,y_train)
dt_reg.fit(X_train ,y_train)

In [ ]:
y_preds_li = li_reg.predict(X_test)
y_preds_lo = lo_reg.predict(X_test)
y_preds_rf = rf_reg.predict(X_test)
y_preds_gb = gb_reg.predict(X_test)
y_preds_dt = dt_reg.predict(X_test)
#y_preds = lo_reg.predict(X_test)
#y_preds = rf_reg.predict(X_test)

In [ ]:
y_preds.shape

In [ ]:
def mse_AIFrenz(y_true, y_pred):
    '''
    y_true: 실제 값
    y_pred: 예측 값
    '''
    diff = abs(y_true - y_pred)
    
    less_then_one = np.where(diff < 1, 0, diff)
    
    # multi-column일 경우에도 계산 할 수 있도록 np.average를 한번 더 씌움
    score = np.average(np.average(less_then_one ** 2, axis = 0))
    
    return score

In [ ]:
print('\n',mse_AIFrenz(y_test, y_preds_li))
print('\n',mse_AIFrenz(y_test, y_preds_lo))
print('\n',mse_AIFrenz(y_test, y_preds_rf))
print('\n',mse_AIFrenz(y_test, y_preds_gb))
print('\n',mse_AIFrenz(y_test, y_preds_dt))

In [ ]:
prediction = li_reg.predict(X_test)

In [ ]:
prediction_A = rf_reg.predict(test_A)
prediction_B = rf_reg.predict(test_B)
prediction_C = rf_reg.predict(test_C)
prediction_D = rf_reg.predict(test_D)
prediction_E = rf_reg.predict(test_E)

In [ ]:
prediction_A.shape

In [ ]:
predict = prediction_A+prediction_B+prediction_C+prediction_D+prediction_E
predict

In [ ]:
predict = predict/5
predict

In [ ]:
predict.shape

In [ ]:
prediction_test

In [140]:
submission.shape

(11520, 2)

In [172]:
predDF = pd.DataFrame(data=pred)

In [173]:
predDF

                          0
date
2020-02-03 00:00  21.912198
2020-02-03 00:10  21.904320
2020-02-03 00:20  21.896286
2020-02-03 00:30  21.808102
2020-02-03 00:40  21.789781
2020-02-03 00:50  21.761332
2020-02-03 01:00  21.742766
2020-02-03 01:10  21.674091
2020-02-03 01:20  21.555315
2020-02-03 01:30  21.546447
2020-02-03 01:40  21.527492
2020-02-03 01:50  21.488459
2020-02-03 02:00  21.491550
2020-02-03 02:10  21.444498
2020-02-03 02:20  21.437226
2020-02-03 02:30  21.369747
2020-02-03 02:40  21.292077
2020-02-03 02:50  21.284231
2020-02-03 03:00  21.246221
2020-02-03 03:10  21.218060
2020-02-03 03:20  21.159760
2020-02-03 03:30  21.161330
2020-02-03 03:40  21.162782
2020-02-03 03:50  21.174124
2020-02-03 04:00  21.097561
2020-02-03 04:10  21.090829
2020-02-03 04:20  21.043854
2020-02-03 04:30  20.976649
2020-02-03 04:40  20.979232
2020-02-03 04:50  20.951619
...                     ...
2020-04-22 19:00  27.560000
2020-04-22 19:10  27.460000
2020-04-22 19:20  27.160000
2020-04-22 19:30  26.920000
2020-04-22 19:40  26.800000
2020-04-22 19:50  26.660000
2020-04-22 20:00  26.600000
2020-04-22 20:10  26.340000
2020-04-22 20:20  26.200000
2020-04-22 20:30  26.080000
2020-04-22 20:40  25.940000
2020-04-22 20:50  25.880000
2020-04-22 21:00  25.840000
2020-04-22 21:10  25.740000
2020-04-22 21:20  25.820000
2020-04-22 21:30  25.740000
2020-04-22 21:40  25.740000
2020-04-22 21:50  25.640000
2020-04-22 22:00  25.600000
2020-04-22 22:10  25.580000
2020-04-22 22:20  25.560000
2020-04-22 22:30  25.460000
2020-04-22 22:40  25.500000
2020-04-22 22:50  25.500000
2020-04-22 23:00  25.520000
2020-04-22 23:10  25.540000
2020-04-22 23:20  25.840000
2020-04-22 23:30  25.700000
2020-04-22 23:40  25.680000
2020-04-22 23:50  25.660000

[11520 rows x 1 columns]

In [139]:
pred = test[['X00','X07','X28','X31','X32', 'A','B','C','D','E']].mean(axis=1)
pred.shape

(11520,)

In [167]:
pred.count()

11520

In [170]:
submission['a'] = pred

In [171]:
submission

          id  Y18   a
0       4752  NaN NaN
1       4753  NaN NaN
2       4754  NaN NaN
3       4755  NaN NaN
4       4756  NaN NaN
5       4757  NaN NaN
6       4758  NaN NaN
7       4759  NaN NaN
8       4760  NaN NaN
9       4761  NaN NaN
10      4762  NaN NaN
11      4763  NaN NaN
12      4764  NaN NaN
13      4765  NaN NaN
14      4766  NaN NaN
15      4767  NaN NaN
16      4768  NaN NaN
17      4769  NaN NaN
18      4770  NaN NaN
19      4771  NaN NaN
20      4772  NaN NaN
21      4773  NaN NaN
22      4774  NaN NaN
23      4775  NaN NaN
24      4776  NaN NaN
25      4777  NaN NaN
26      4778  NaN NaN
27      4779  NaN NaN
28      4780  NaN NaN
29      4781  NaN NaN
...      ...  ...  ..
11490  16242  NaN NaN
11491  16243  NaN NaN
11492  16244  NaN NaN
11493  16245  NaN NaN
11494  16246  NaN NaN
11495  16247  NaN NaN
11496  16248  NaN NaN
11497  16249  NaN NaN
11498  16250  NaN NaN
11499  16251  NaN NaN
11500  16252  NaN NaN
11501  16253  NaN NaN
11502  16254  NaN NaN
11503  16255  NaN NaN
11504  16256  NaN NaN
11505  16257  NaN NaN
11506  16258  NaN NaN
11507  16259  NaN NaN
11508  16260  NaN NaN
11509  16261  NaN NaN
11510  16262  NaN NaN
11511  16263  NaN NaN
11512  16264  NaN NaN
11513  16265  NaN NaN
11514  16266  NaN NaN
11515  16267  NaN NaN
11516  16268  NaN NaN
11517  16269  NaN NaN
11518  16270  NaN NaN
11519  16271  NaN NaN

[11520 rows x 3 columns]

In [135]:
submission.to_csv('data/submission_0404_1.csv', index=False)

In [ ]:
predDF

In [176]:
predDF.to_csv('data/submission_0404_1.csv', index=False)